[advisories]
git-fetch-with-cli = true

[licenses]
unlicensed = "deny"
copyleft = "deny"
allow = [
  "MIT",
  "Apache-2.0",
]
exceptions = [
  { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
  { allow = ["ISC"], name = "is_ci" },
  { allow = ["BSD-3-Clause"], name = "encoding_rs" },
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
  { path = "LICENSE", hash = 0xbd0eed23 },
]
