on: workflow_dispatch
name: build
jobs:
  linux-amd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: ".bin"
      - name: Build
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: x86_64-unknown-linux-gnu
          path: |
            target/x86_64-unknown-linux-gnu/release/oatmeal
            target/x86_64-unknown-linux-gnu/release/oatmeal.dwp

  linux-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: ".bin"
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu
      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install gcc-aarch64-linux-gnu
          rustup target add aarch64-unknown-linux-gnu
          cargo install cargo-run-bin
          cargo zigbuild --release --target aarch64-unknown-linux-gnu
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: aarch64-unknown-linux-gnu
          path: |
            target/aarch64-unknown-linux-gnu/release/oatmeal
            target/aarch64-unknown-linux-gnu/release/oatmeal.dwp

  macos-amd:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: ".bin"
      - name: Build
        run: |
          cargo build --release --target x86_64-apple-darwin
          cd target/x86_64-apple-darwin/release/
          cp -r "$(readlink oatmeal.dSYM)" symbols
          rm oatmeal.dSYM
          mv symbols oatmeal.dSYM
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: x86_64-apple-darwin
          path: |
            target/x86_64-apple-darwin/release/oatmeal
            target/x86_64-apple-darwin/release/oatmeal.dSYM

  macos-arm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: ".bin"
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin
      - name: Build
        run: |
          rustup target add aarch64-apple-darwin
          cargo install cargo-run-bin
          cargo zigbuild --release --target aarch64-apple-darwin
          cd target/aarch64-apple-darwin/release
          cp -r "$(readlink oatmeal.dSYM)" symbols
          rm oatmeal.dSYM
          mv symbols oatmeal.dSYM
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: aarch64-apple-darwin
          path: |
            target/aarch64-apple-darwin/release/oatmeal
            target/aarch64-apple-darwin/release/oatmeal.dSYM

  windows-amd:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: ".bin"
      - name: Build
        run: |
          cargo build --profile release-windows --target x86_64-pc-windows-msvc
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: x86_64-pc-windows-msvc
          path: |
            target/x86_64-pc-windows-msvc/release-windows/oatmeal.exe
            target/x86_64-pc-windows-msvc/release-windows/oatmeal.pdb

  windows-arm:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-pc-windows-msvc
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: ".bin"
      - name: Build
        run: |
          rustup target add aarch64-pc-windows-msvc
          cargo build --profile release-windows --target aarch64-pc-windows-msvc
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: aarch64-pc-windows-msvc
          path: |
            target/aarch64-pc-windows-msvc/release-windows/oatmeal.exe
            target/aarch64-pc-windows-msvc/release-windows/oatmeal.pdb
